CC = gcc

PROGRAMS = 10-01 10-02 10-03 10-04 10-05 10-06 10-07 10-08 10-09 10-10

all: $(PROGRAMS)

10-01: 10-01.c
	$(CC) -Wall -o $@ $^

10-02: 10-02.c
	$(CC) -Wall -o $@ $^

10-03: 10-03.c
	$(CC) -Wall -o $@ $^

10-04: 10-04.c
	$(CC) -Wall -o $@ $^

10-05: 10-05.c
	$(CC) -Wall -o $@ $^

10-06: 10-06.c
	$(CC) -Wall -o $@ $^

10-07: 10-07.c
	$(CC) -Wall -o $@ $^

10-08: 10-08.c
	$(CC) -Wall -o $@ $^

10-09: 10-09.c
	$(CC) -Wall -o $@ $^

10-10: 10-10.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
