CC = gcc

PROGRAMS = 3-01-1 3-01-2 3-02

all: $(PROGRMAS)

3-01-1: 3-01-1.c
	$(CC) -Wall -o $@ $^

3-01-2: 3-01-2.c
	$(CC) -Wall -o $@ $^

3-02: 3-02.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
