CC = gcc 

PROGRAMS = 6-01 6-02 6-03 6-04 6-05 6-06 6-07 6-08 6-09 6-10 \
	   6-11 6-12 6-13

all: $(PROGRAMS)

6-01: 6-01.c
	$(CC) -Wall -o $@ $^

6-02: 6-02.c
	$(CC) -Wall -o $@ $^

6-03: 6-03.c
	$(CC) -Wall -o $@ $^

6-04: 6-04.c
	$(CC) -Wall -o $@ $^

6-05: 6-05.c
	$(CC) -Wall -o $@ $^

6-06: 6-06.c
	$(CC) -Wall -o $@ $^

6-07: 6-07.c
	$(CC) -Wall -o $@ $^

6-08: 6-08.c
	$(CC) -Wall -o $@ $^

6-09: 6-09.c
	$(CC) -Wall -o $@ $^

6-10: 6-10.c
	$(CC) -Wall -o $@ $^

6-11: 6-11.c
	$(CC) -Wall -o $@ $^

6-12: 6-12.c
	$(CC) -Wall -o $@ $^

6-13: 6-13.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
