CC = gcc

PROGRAMS = 3-01 3-02 3-03 3-04 3-05 3-06 3-07 3-08 3-09 3-10 3-11

all: $(PROGRAMS)

3-01: 3-01.c
	$(CC) -Wall -o $@ $^

3-02: 3-02.c
	$(CC) -Wall -o $@ $^

3-03: 3-03.c
	$(CC) -Wall -o $@ $^

3-04: 3-04.c
	$(CC) -Wall -o $@ $^

3-05: 3-05.c
	$(CC) -Wall -o $@ $^

3-06: 3-06.c
	$(CC) -Wall -o $@ $^

3-07: 3-07.c
	$(CC) -Wall -o $@ $^

3-08: 3-08.c
	$(CC) -Wall -o $@ $^

3-09: 3-09.c
	$(CC) -Wall -o $@ $^

3-10: 3-10.c
	$(CC) -Wall -o $@ $^

3-11: 3-11.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
