CC = gcc

PROGRAMS = 9-01 9-02 9-03 9-04 9-05

all: $(PROGRAMS)

9-01: 9-01.c
	$(CC) -Wall -o $@ $^

9-02: 9-02.c
	$(CC) -Wall -o $@ $^

9-03: 9-03.c
	$(CC) -Wall -o $@ $^

9-04: 9-04.c
	$(CC) -Wall -o $@ $^

9-05: 9-05.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
