CC = gcc

PROGRAMS = 7-01 7-02 7-03 7-04 7-05 7-06 7-07 7-08 7-09

all: $(PROGRAMS)

7-01: 7-01.c
	$(CC) -Wall -o $@ $^

7-02: 7-02.c
	$(CC) -Wall -o $@ $^

7-03: 7-03.c
	$(CC) -Wall -o $@ $^

7-04: 7-04.c
	$(CC) -Wall -o $@ $^

7-05: 7-05.c
	$(CC) -Wall -o $@ $^

7-06: 7-06.c
	$(CC) -Wall -o $@ $^

7-07: 7-07.c
	$(CC) -Wall -o $@ $^

7-08: 7-08.c
	$(CC) -Wall -o $@ $^

7-09: 7-09.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
